### ISSUE TITLE
index.json vs /cms-data-index.json

### ISSUE THREAD

**Issue by jondaiello** [CMSgov/QHP-provider-formulary-APIs#23]
According to the index.html and the index_document.md, there appear to be references to two different index files. Is this correct, or are the index.json and the cms-data-index.json one in the same?

**Comment by DanReinders** [comment]
There are multiple references to both index.json and cms-data-index.json.

/developer/index.html and /README.md both refer to index.json

/index.html and /index_document.md both refer to cms-data-index.json

It looks to me like cms-data-index.json is the correct name for the index file but clarification would be very helpful.

**Comment by alexdresko** [comment]
We just submitted cms-data.index.json yesterday an it worked... but it doesn't look like the file name matters at all during the submission process.

**Comment by greggersh** [comment]
Yes, the file name does not matter.
